### ISSUE TITLE
Reference count EphemeralPanes

### ISSUE THREAD

**Issue by ObserverHerb** [EngineeringDeck/Celeste#25]
EphemeralPanes should have a Destroy() function that decrements a reference count and calls deleteLater() on itself when it's time. Or perhaps a "valid" boolean or something to that effect. This allows the Finished() signal to fire multiple times without creating chaos.

**Comment by herbmillerjr** [comment]
Might be able to just key off of show/hide for this.

**Comment by herbmillerjr** [comment]
Should ReleaseEphemeralPane just take the pointer as a parameter instead of relying on the end of the queue to be valid?

Should we be comparing the pane passed in with what's in the end of the queue and if they don't match, flush the queue, perhaps?

**Comment by herbmillerjr** [comment]
Even better, we shouldn't rely on Finished() signal for popping a pane off the queue. Rely on destroy(), which will only be called by deleteLater(), which is attached to Finished() but only fires once.
